# -*- coding: utf-8 -*-
"""Labsheet2-flicker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CrFJSDzM-gavqsVctS657alKqHu-7Xxf
"""

import pandas as pd
df_data=pd.read_csv("/content/drive/MyDrive/datasets/BL-Flickr-Images-Book.csv")
print(df_data.head())

import pandas as pd
import numpy as np
from functools import reduce

df_data=pd.read_csv("/content/drive/MyDrive/datasets/BL-Flickr-Images-Book.csv")
print(df_data.head)

for col in df_data.columns:
  print(col)

to_drop=["Edition Statement"]
df_data.drop(to_drop,inplace=True,axis=1)
print(df_data.head())