# -*- coding: utf-8 -*-
"""labsheet-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LVic6xAx4TYzSw2h6U2Vv--_egqX4Trc
"""

import pandas as pd
s1=pd.Series([-3,-1,1,35,'gaurav',7.3])
print(s1)

print(s1[2])

a=[1,7,2]
myvar=pd.Series(a,index=['x','y','z'])
print(myvar)
print(myvar["y"])

calories={"day1":420,"day2":380,"day3":390}
myvar=pd.Series(calories)
print(myvar)

s1[:2]

print(s1[[2,0,1]])

data={}