# -*- coding: utf-8 -*-
"""Labsheet-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bKSqMHYc061-IWKaSvGDwFEdyjWbwohu
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/datasets/data (1).csv")
print(df.head(5))

df.shape

df.isnull()

print(df.isnull().sum())

print(df.fillna(130,inplace=True))

print(df.to_markdown())

df=pd.read_csv("/content/drive/MyDrive/datasets/data (1).csv")
print(df.head())

x=df["Calories"].mode()[0]
df["Calories"].fillna(x,inplace=True)
print(df.to_markdown())

x=df["Calories"].mean()
df["Calories"].fillna(x,inplace=True)
print(df.to_markdown())

x=df["Calories"].median()
df["Calories"].fillna(x,inplace=True)
print(df.to_markdown())

df=pd.read_csv("/content/drive/MyDrive/datasets/data (1).csv")
print(df.head())

df=pd.read_csv("/content/drive/MyDrive/datasets/data (1).csv")
print(df.head())





x=df["Calories"].median()
df["Calories"].fillna(x,inplace=True)
print(df.to_markdown())

df.corr()

import pandas as pd
print(df.drop_duplicates(inplace=True))