# -*- coding: utf-8 -*-
"""LabSheet3-PandasSeries.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hv2ojZ-w4YkxR_bNLGkLBE_TBGOULQSU
"""

import pandas as pd
a=[1,7.2,2]
myvar=pd.Series(a)
print(myvar)



"""### ***`[To return first value of the series](https://)`***"""

print(myvar[0])

"""## Create ***Lables***"""

a=[1,7,2]
myvar=pd.Series(a,index=["x","y","z"])
print(myvar)

"""***Return value of "y"***"""

print(myvar["y"])

thisdict={
    "Aamina":"Fathima",
    "Eldest":"Youngest",
    "Year":"2023"
}
print(thisdict)