# -*- coding: utf-8 -*-
"""Network_Visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1D-zdr0lb9ZQEwaZEDeuVeZlGDifCXLHI
"""

import networkx as nx
import matplotlib.pyplot as plt

import networkx as nx
import matplotlib.pyplot as plt
G=nx.Graph()
G.add_nodes_from([1,2,3,4,5])
G.add_edges_from([(1,2),(1,3),(2,3),(3,4),(5,1)])
pos=nx.spring_layout(G)
nx.draw(G,pos,with_labels=True,node_color='pink',node_size=1400,edge_color='purple',width=5,font_size=10)
plt.show()

G=nx.Graph()

G.add_nodes_from([1,2,3,4,5])

G.add_edges_from([(1,2),(1,3),(2,3),(3,4)(5,1)])