# -*- coding: utf-8 -*-
"""Scalar visualization.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Et6IhBYSaBYI_Uem800nwcNdGerm4Szp
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
data=pd.DataFrame({
    "x":np.random.rand(100),
    "y":np.random.rand(100),
    "value":np.random.rand(100)
})
cmap="magma"
alpha=1
plt.figure(figsize=(6,6))
plt.scatter(data["x"],data["y"],c=data["value"],cmap=cmap,alpha=alpha)
plt.xlabel("X-axis")
plt.ylabel("Y-axis")
plt.title("Scatter plot with Colormap")
plt.colorbar(label="value")
plt.show

#Contouring
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
#Generate some random data for contouring
data=pd.DataFrame(np.random.rand(10,10))
#plot Contours
plt.figure(figsize=(6,6))
plt.contour(data.values)
plt.show()

#heigh plots
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
#generate somerandomdata for demonstartion
data=pd.DataFrame(np.random.rand(10,10))
#create meshgrid for x and y coordinates
x=np.arange(data.shape[0])
y=np.arange(data.shape[1])
X,Y=np.meshgrid(x,y)
#plot height plot
fig=plt.figure(figsize=(10,8))
ax=fig.add_subplot(111,projection='3d')
ax.plot_surface(X,Y,data.values,cmap="plasma")
plt.show()

